branch-defaults:
  default:
    environment: api-env
environment-defaults:
  api-env:
    branch: null
    repository: null
global:
  application_name: CatOrBird
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application